// screen sizes
export const MOBILE_MAX_WIDTH_SCREEN_SIZE = '480px';
export const TABLET_SM_MIN_WIDTH_SCREEN_SIZE = MOBILE_MAX_WIDTH_SCREEN_SIZE + 1; //481
export const TABLET_SM_MAX_WIDTH_SCREEN_SIZE = '767px';

export const TABLET_MIN_WIDTH_SCREEN_SIZE = TABLET_SM_MAX_WIDTH_SCREEN_SIZE + 1; // 768
export const TABLET_MAX_WIDTH_SCREEN_SIZE = '1024px';

export const DESKTOP_MIN_WIDTH_SCREEN_SIZE = TABLET_MAX_WIDTH_SCREEN_SIZE + 1; // 1025

export const PER_PAGE = 8;


